"""
FloodCast Gurugram — Dataset Expansion (v2)
=============================================
Adds to, but does NOT alter, the original 36-point official-structure
dataset (hotspots.csv / hotspots.parquet, generated by generate_hotspots.py).

WHY THIS FILE EXISTS
---------------------
After extensive searching (MCG/GMDA official coverage, multiple news
archives, GMDA's own site, real-estate portals, tourism sites), NO source
was found confirming an official "72 hotspots" figure for Gurugram. What
IS confirmed, from GMDA's own reporting, is a SEPARATE tracking system
from MCG's: GMDA brought its own master-road flood-prone-point count down
from 79 (2020) to 16 (2024) — a different authority, different roads,
different number, and no 2026 update found for it specifically. See
DATA_PROVENANCE.md section 6 for the full trail.

So this file does NOT claim to reproduce an official "72-point list" —
because that list doesn't appear to exist publicly. Instead, per the
explicit request, it adds 28 more REAL locations in two honesty tiers:

  TIER B (4 points) — genuinely confirmed via fresh research: named in
  real-estate/civic reporting as experiencing waterlogging, just not part
  of MCG's specific 36-point classification.

  TIER C (24 points) — real, verifiable Gurugram localities (they
  genuinely exist — this is not invented geography) included because they
  sit on low-lying or high-runoff ground near known-bad corridors, per the
  explicit ask to include real places that "may cause problems in very
  severe rain" even without a specific news citation confirming they have.
  These are lower-confidence than anything in the original 36 and are
  tagged accordingly — treat them as a watchlist, not a verified list.

Also adds a SEPARATE attractions.csv/.parquet — real, multi-source-
confirmed Gurugram landmarks. These are not flood classifications at all;
they exist so the app is useful as a general "is this place reachable"
tool, not just a hazard map.
"""

import pandas as pd
import numpy as np

RNG = np.random.default_rng(seed=43)  # different seed from the base 36, still reproducible

TIER_PARAMS = {
    "hypercritical": dict(threshold_mm=(15, 22), time_to_flood_min=(20, 40),
                           drain_hr=(3.0, 6.0), drainage_score=(0.10, 0.30)),
    "moderate":       dict(threshold_mm=(25, 35), time_to_flood_min=(40, 90),
                           drain_hr=(1.5, 3.0), drainage_score=(0.35, 0.60)),
    "minor":          dict(threshold_mm=(40, 55), time_to_flood_min=(90, 150),
                           drain_hr=(0.5, 1.5), drainage_score=(0.65, 0.85)),
}

def synth_fields(tier: str) -> dict:
    p = TIER_PARAMS[tier]
    return dict(
        rainfall_threshold_mm_per_hr=round(RNG.uniform(*p["threshold_mm"]), 1),
        time_to_flood_after_threshold_min=int(RNG.uniform(*p["time_to_flood_min"])),
        typical_drain_time_hr=round(RNG.uniform(*p["drain_hr"]), 1),
        drainage_capacity_score=round(RNG.uniform(*p["drainage_score"]), 2),
    )

# ---------------------------------------------------------------------------
# TIER B — confirmed real via this round's research, not in MCG's 36
# ---------------------------------------------------------------------------
TIER_B = [
    dict(name="Golf Course Road", locality="DLF area, Central Gurugram", zone="Zone 2",
         tier="moderate", lat=28.4380, lon=77.1010,
         confidence="confirmed_named_multi_source",
         source="99acres locality review (2026) — 'poor drainage leads to waterlogging on Golf Course Road itself', distinct from Golf Course Extension Road already in the base 36",
         road_type="arterial", commute_relevance="High"),
    dict(name="Judges Enclave (Golf Course Road)", locality="DLF area, Central Gurugram",
         zone="Zone 2", tier="moderate", lat=28.4360, lon=77.1030,
         confidence="confirmed_named_multi_source",
         source="99acres locality review (2026) — 'Judges Enclave along the road faces waterlogging post-rain'",
         road_type="residential colony road", commute_relevance="Medium"),
    dict(name="Dwarka Expressway (Sectors 112-115)", locality="New Gurugram, Dwarka Expressway belt",
         zone="Zone 2", tier="moderate", lat=28.5150, lon=77.0450,
         confidence="confirmed_named_multi_source",
         source="GMDA-approved drainage project coverage (2026) — ~7.59km stormwater system approved specifically because these sectors 'have faced waterlogging'",
         road_type="expressway / under-development sectors", commute_relevance="High"),
    dict(name="Old Delhi-Gurgaon Road (Mahavir Chowk-Kapashera)", locality="North Gurugram",
         zone="Zone 1", tier="moderate", lat=28.5050, lon=77.0650,
         confidence="confirmed_named_multi_source",
         source="GMDA drainage project coverage (April 2026) — 7.5km corridor targeted specifically for 'chronic waterlogging'",
         road_type="arterial corridor", commute_relevance="High"),
]

# ---------------------------------------------------------------------------
# TIER C — real, verifiable Gurugram localities; PLAUSIBLE severe-rain risk,
# not confirmed by any source found. Lower confidence than Tier A or B.
# ---------------------------------------------------------------------------
TIER_C = [
    dict(name="Sushant Lok 1", locality="Central Gurugram", zone="Zone 1", tier="moderate",
         lat=28.4680, lon=77.0850, road_type="residential colony road", commute_relevance="Medium"),
    dict(name="Malibu Town (Sohna Road)", locality="South Gurugram", zone="Zone 2", tier="moderate",
         lat=28.4130, lon=77.0480, road_type="residential colony road, adjacent to Sohna Road", commute_relevance="Medium"),
    dict(name="Vatika City (Sohna Road)", locality="South Gurugram", zone="Zone 2", tier="moderate",
         lat=28.3980, lon=77.0380, road_type="residential colony road, adjacent to Sohna Road", commute_relevance="Medium"),
    dict(name="Nirvana Country (Sohna Road)", locality="South Gurugram", zone="Zone 2", tier="minor",
         lat=28.4230, lon=77.0510, road_type="residential colony road", commute_relevance="Low"),
    dict(name="DLF Phase 1 Internal Road", locality="Central Gurugram", zone="Zone 1", tier="minor",
         lat=28.4790, lon=77.0920, road_type="internal road", commute_relevance="Medium"),
    dict(name="DLF Phase 4 (Galleria Market)", locality="Central Gurugram", zone="Zone 1", tier="minor",
         lat=28.4700, lon=77.1000, road_type="commercial internal road", commute_relevance="Medium"),
    dict(name="Palam Vihar Main Market", locality="West Gurugram", zone="Zone 1", tier="minor",
         lat=28.5020, lon=76.9970, road_type="sector market road", commute_relevance="Medium"),
    dict(name="South City 1 Internal Road", locality="Central Gurugram", zone="Zone 2", tier="minor",
         lat=28.4460, lon=77.0480, road_type="internal road", commute_relevance="Low"),
    dict(name="Sector 14 Market", locality="Old Gurugram", zone="Zone 1", tier="minor",
         lat=28.4740, lon=77.0280, road_type="sector market road", commute_relevance="Medium"),
    dict(name="Sector 17 Market", locality="Old Gurugram", zone="Zone 1", tier="minor",
         lat=28.4770, lon=77.0480, road_type="sector market road", commute_relevance="Medium"),
    dict(name="Sector 22 (near HUDA)", locality="Old Gurugram", zone="Zone 1", tier="minor",
         lat=28.4640, lon=77.0330, road_type="sector internal", commute_relevance="Low"),
    dict(name="Sector 23A Industrial Area", locality="Old Gurugram", zone="Zone 1", tier="minor",
         lat=28.4900, lon=77.0180, road_type="industrial road", commute_relevance="Medium"),
    dict(name="Sector 31 Market", locality="Old Gurugram", zone="Zone 1", tier="minor",
         lat=28.4520, lon=77.0300, road_type="sector market road", commute_relevance="Low"),
    dict(name="Sector 40 (near Golf Course Rd)", locality="Central Gurugram", zone="Zone 2",
         tier="minor", lat=28.4460, lon=77.0900, road_type="sector internal", commute_relevance="Low"),
    dict(name="Sector 45", locality="South-Central Gurugram", zone="Zone 2", tier="minor",
         lat=28.4340, lon=77.0870, road_type="sector internal", commute_relevance="Low"),
    dict(name="Sector 46 (Sohna Road belt)", locality="South Gurugram", zone="Zone 2", tier="minor",
         lat=28.4210, lon=77.0680, road_type="sector internal", commute_relevance="Low"),
    dict(name="Sector 57 (near Golf Course Ext Rd)", locality="South-East Gurugram", zone="Zone 2",
         tier="minor", lat=28.4180, lon=77.0900, road_type="sector internal", commute_relevance="Medium"),
    dict(name="Sector 82 (Dwarka Expressway belt)", locality="New Gurugram", zone="Zone 2",
         tier="minor", lat=28.4970, lon=76.9980, road_type="sector internal, under development", commute_relevance="Low"),
    dict(name="Sector 109 (Dwarka Expressway belt)", locality="New Gurugram", zone="Zone 2",
         tier="minor", lat=28.5100, lon=77.0300, road_type="sector internal, under development", commute_relevance="Low"),
    dict(name="Manesar Chowk", locality="Manesar (South-West edge of city)", zone="Zone 2",
         tier="minor", lat=28.3550, lon=76.9350, road_type="industrial town junction", commute_relevance="Medium"),
    dict(name="Kherki Daula Toll Plaza", locality="NH-48, South-West edge of city", zone="Zone 2",
         tier="minor", lat=28.3900, lon=76.9700, road_type="NH-48 toll plaza", commute_relevance="High"),
    dict(name="Sector 105 (Dwarka Expressway belt)", locality="New Gurugram", zone="Zone 2",
         tier="minor", lat=28.5080, lon=76.9900, road_type="sector internal, under development", commute_relevance="Low"),
    dict(name="IMT Manesar Main Road", locality="Manesar industrial belt", zone="Zone 2",
         tier="minor", lat=28.3700, lon=76.9600, road_type="industrial arterial", commute_relevance="Medium"),
    dict(name="Sector 56 Extension", locality="South-East Gurugram", zone="Zone 2", tier="minor",
         lat=28.4270, lon=77.1080, road_type="sector internal", commute_relevance="Low"),
]

# ---------------------------------------------------------------------------
# ATTRACTIONS — separate table, not part of the flood-risk register at all
# ---------------------------------------------------------------------------
ATTRACTIONS = [
    dict(name="Kingdom of Dreams", category="Entertainment", locality="Sector 29",
         lat=28.4670, lon=77.0680,
         source="Multiple tourism sources — India's first live entertainment/theatre destination"),
    dict(name="Cyber Hub", category="Dining & Nightlife", locality="DLF Phase 2",
         lat=28.4950, lon=77.0900,
         source="Multiple tourism sources — major F&B/entertainment complex, adjacent to Cyber City hotspot"),
    dict(name="Ambience Mall", category="Shopping", locality="NH-8 / Delhi border",
         lat=28.5010, lon=77.0940,
         source="Multiple tourism sources — one of the largest malls in the country"),
    dict(name="Leisure Valley Park", category="Park", locality="Sector 29",
         lat=28.4650, lon=77.0630,
         source="Multiple tourism sources — 101-acre urban park with musical fountains"),
    dict(name="Aravalli Biodiversity Park", category="Park / Nature", locality="Near Guru Dronacharya Metro",
         lat=28.4750, lon=77.0980,
         source="Multiple tourism sources — 380-acre ecological restoration park"),
    dict(name="Sheetla Mata Mandir", category="Religious", locality="Gurgaon-Sohna Road",
         lat=28.4230, lon=77.0350,
         source="Multiple tourism sources — one of the most revered temples in the region"),
    dict(name="Galleria Market", category="Shopping", locality="DLF Phase 4",
         lat=28.4700, lon=77.1000,
         source="Multiple tourism sources — boutique/cafe shopping district"),
    dict(name="Sultanpur National Park", category="Park / Nature", locality="Farrukhnagar Road (edge of city)",
         lat=28.4600, lon=76.8950,
         source="Multiple tourism sources — bird sanctuary, ~15km from central Gurugram"),
]

# ---------------------------------------------------------------------------
# BUILD
# ---------------------------------------------------------------------------
def build_rows(records, confidence_default=None, start_id=37):
    rows = []
    for i, h in enumerate(records, start=start_id):
        conf = h.get("confidence", confidence_default)
        row = {
            "hotspot_id": f"FCG-{i:03d}",
            "name": h["name"],
            "locality_area": h["locality"],
            "zone": h["zone"],
            "severity_tier": h["tier"],
            "latitude": h["lat"],
            "longitude": h["lon"],
            "road_type": h["road_type"],
            "commute_relevance": h["commute_relevance"],
            "data_confidence": conf,
            "source_note": h.get("source", "Real, verifiable Gurugram locality; flood risk is a plausible, UNCONFIRMED estimate based on proximity to known-bad corridors, not a cited source"),
            "coordinates_verified": "No — approximate, verify before production use",
            **synth_fields(h["tier"]),
        }
        rows.append(row)
    return rows

tier_b_rows = build_rows(TIER_B, start_id=37)
tier_c_rows = build_rows(TIER_C, confidence_default="plausible_real_unconfirmed_flood_status",
                          start_id=37 + len(TIER_B))

expansion_df = pd.DataFrame(tier_b_rows + tier_c_rows)
assert len(expansion_df) == 28, f"Expected 28 new rows, got {len(expansion_df)}"

# merge with the original 36 (read fresh from disk, never mutated)
base_df = pd.read_csv("data/hotspots.csv")
full_df = pd.concat([base_df, expansion_df], ignore_index=True)
assert full_df["hotspot_id"].is_unique
assert len(full_df) == 64

full_df.to_csv("data/hotspots_extended.csv", index=False)
full_df.to_parquet("data/hotspots_extended.parquet", index=False)

# attractions — separate file, separate schema, no flood-risk fields
attractions_df = pd.DataFrame([
    {**a, "poi_id": f"FCG-POI-{i:02d}"} for i, a in enumerate(ATTRACTIONS, start=1)
])
attractions_df.to_csv("data/attractions.csv", index=False)
attractions_df.to_parquet("data/attractions.parquet", index=False)

print(f"Extended risk register: {len(full_df)} rows "
      f"({len(base_df)} original + {len(expansion_df)} new: "
      f"{len(TIER_B)} confirmed + {len(TIER_C)} plausible-unconfirmed)")
print(f"Attractions POI table: {len(attractions_df)} rows")
print()
print("Confidence breakdown, full register:")
print(full_df["data_confidence"].value_counts().to_string())
